"use client";

import jsPDF from "jspdf";


export default function ReportButton({actor}: any) {


function generateReport(){


const doc = new jsPDF();



doc.setFontSize(20);

doc.text(
"ThreatScope Intelligence Report",
20,
20
);



doc.setFontSize(12);


doc.text(
`Threat Actor: ${actor.name}`,
20,
40
);



doc.text(
`Risk Level: High`,
20,
55
);



doc.text(
`Malware: ${actor.malware.join(", ")}`,
20,
70
);



doc.text(
`MITRE Techniques: ${actor.techniques.join(", ")}`,
20,
85
);



doc.text(
`IOC: ${actor.iocs.join(", ")}`,
20,
100
);



doc.text(
"Generated by ThreatScope",
20,
130
);



doc.save(
`${actor.name}-Threat-Report.pdf`
);



}



return (

<button

onClick={generateReport}

className="
mt-5
bg-cyan-500
text-black
font-bold
px-5
py-3
rounded-lg
hover:bg-cyan-400
"

>

Generate Intelligence Report

</button>


);


}